---
title: "testRMarkdownDocument"
author: "JG"
date: "19/03/2021"
output: html_document
---

Basic Data Analysis in RStudio - https://www.youtube.com/watch?v=0pwRxhxG0tg

```{r}
setwd("/home/josh/testArea")
mydata <- read.csv("mroz.csv",na.string = ".")

# summary stats
summary(mydata)
# correlations
cor(mydata)
```

```{r}
# dealing with missing values
# correlation between education & wage --> doesn't help us as there are many null values for wage
cor(mydata[c('educ','wage')])

# look at cor using "?cor" in the console
# we find that cor contains a "use" argument which determines how we compute covariance
# complete tells R to only use observations where all variables are present (ignoring nulls)
cor(mydata[c('educ','wage')],use="complete")
```

```{r}
# Summary Stats for selected variables
## Options 1
#summary(mydata[c('hours','husage')])
#cor(mydata[c('educ','motheduc','fatheduc')])

## Option 2 using subsets
# note the "." here doesn't have a special meaning, we're just using it to describe a subset of mydata
mydata.sub0 <- subset(mydata, select=c("hours","husage"))
#summary(mydata.sub0)
#cor(mydata.sub0)

# what if we want to restrict our subset to cases where people work? (hours larger than 0)
# mydata$hours > 0
#mydata.sub1 <- subset(mydata, hours>0)
#cor(mydata.sub1[c("educ","wage")])
# which is equivalent to
mydata.sub1 <- subset(mydata, hours>0, select=c("educ","wage"))
cor(mydata.sub1)
```

```{r}
# More summary stats
## Categorical variables
#install.packages('mosaic')
require(mosaicCore)
#library(mosaicCore)

```

```{r}
# kidslt6 is a column describing the number of children 5 years or younger
#counts
#i.e. select count i by kidslt6 from mydata
tally(~kidslt6, data=mydata,margins=TRUE)
#percent
tally(~kidslt6, data=mydata,margins=TRUE,format="perc")
#proportions
tally(~kidslt6, data=mydata,margins=TRUE,format="prop")

## Contingency Tables (Cross Tables)
tally(~kidsge6+kidslt6, data=mydata,margins=TRUE)
## Conditionals
# people with less education seem to have more children
tally(~kidsge6|educ>=16, data=mydata,margins=TRUE,format="prop")

##Continuous Variables
mean(~wage, data=mydata, na.rm=TRUE)
favstats(~wage,data=mydata)
```